name: tfl_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/tnc1997/dart-tfl-api-client
author: Thomas Clark

environment:
  sdk: '>=2.0.0 <3.0.0'

# dependencies:
#   path: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
